# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0503330c8dcab1ed9c4840904400cb18f109b72c7734aaca7fa2126058310105a2fdd3bf8e568e7453ba1e9f8de9b6cc7f2254fbbf9fb78b5f7133d3a9a3b67a

test:
  secret_key_base: bb637bba454fab94c0aa73ed5e2f06e4fff4777d5707cad0df5d6022a6798506d65d1e65390e4788954bebf1424a595e33b1aae8e5154bafca91ec9c0f556c2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
